### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by tigertv** [jubalh/nudoku#17]

**Comment by jubalh** [comment]
Not sure what should be written in them :) So far it seems like people (like you) were able to just contribute.

**Comment by tigertv** [comment]
You can add something like what you gave me https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53.

**Comment by jubalh** [comment]
Honestly I don't think it's needed :)
It's just standard git best practice.

**Comment by tigertv** [comment]
Could I do that way https://github.com/jquery/jquery/commit/45f085882597016e521436f01a8459daf3e4000e

**Comment by jubalh** [comment]
If I understandthat right, its checking the licenses the projects is licensed under. So that people who want to use jquery as a dependency know under which circumstances they can include it in their project.

Since nudoku only uses one license, and that one is in the git repo, and additionally GitHub displays it on the top right corner, I don't think its needed :)

**Comment by tigertv** [comment]
OK.
