### ISSUE TITLE
error: possibly undefined macro: AC_MSG_ERROR when running autoreconf -i

### ISSUE THREAD

**Issue by benalb** [jubalh/nudoku#29]
When trying to build from source tar.gz, I get this:
`
[benalb@void-lite nudoku-2.0.0]$ autoreconf -i
(...)
configure.ac:29: error: possibly undefined macro: AC_MSG_ERROR

      If this token and others are legitimate, please use m4_pattern_allow.

      See the Autoconf documentation.

autoreconf: /usr/bin/autoconf failed with exit status: 1
`

**Comment by jubalh** [comment]
> When trying to build from source tar.gz
Which tarball exactly?

https://github.com/jubalh/nudoku/releases/download/2.0.0/nudoku-2.0.0.tar.gz or https://github.com/jubalh/nudoku/archive/2.0.0.tar.gz ?

> [benalb@void-lite nudoku-2.0.0]$ autoreconf -i

Why do you call autoreconf?

```
./configure
make
```

This should be enough.

**Comment by benalb** [comment]
https://github.com/jubalh/nudoku/archive/2.0.0.tar.gz

**Comment by jubalh** [comment]
I updated the comment above, it might be that you didn't read all of it before replying.

**Comment by benalb** [comment]
I'm trying to build from source, in order to create the template for voidlinux, the 1.0.0 release worked well, but the 2.0.0 is giving errors, so I tried to build it, whit the autoreconf -i error

**Comment by jubalh** [comment]
But why do you run autoreconf, and not only configure and make? Do you have autoconf-archive installed?

**Comment by benalb** [comment]
[benalb@void-lite tmp]$ ls
2.0.0.tar.gz  nudoku-2.0.0  void-packages
[benalb@void-lite tmp]$ cd nudoku-2.0.0/
[benalb@void-lite nudoku-2.0.0]$ ls
AUTHORS  ChangeLog  LICENSE  Makefile.am  README.md  configure.ac  man  po  src

No configure in there. :?

**Comment by benalb** [comment]
ok, the autoconf-archive is not installed. Very sorry. closing the issue.

**Comment by jubalh** [comment]
Ok now again:

If you use the autogenerated tarball from GitHub then there is not configure in there because its not in the git repo.

configure is only specifically prepared tarball.

Do you get errors with the prepared tarball or why don't use use it?

If you use the one prepared from GitHub then you need to run autoreconf. It might be that your distribution has split of the needed packages, this is for you to find out.

It would be helpful if you would answer all the questions I ask you. For example I assume that autoreconf-archive is not installed on you system.

**Comment by jubalh** [comment]
OK, glad that it works. Thanks for packaging nudoku for Void Linux!
