### ISSUE TITLE
please exclude generated files

### ISSUE THREAD

**Issue by agaida** [jubalh/nudoku#6]
it really sucks if one build with tar-balls, a clean will remove these files - so the sources differ to the original tar-ball

<pre>
M       Makefile.in
M       aclocal.m4
M       configure
M       depcomp
M       install-sh
M       missing
M       src/Makefile.in
</pre>

**Comment by jubalh** [comment]
Hi!
So you are downloading the .tar.xz I take it.
This get's created with make dist-xz and as far as I know those files should be in there so a user only has to run `./configure && make`. If I understood it corrtectly those files sould only change if you run `autoreconf -i` or similar. And I thought exactly to prevent the user from having to do this there is this way of generating before them.

I am not sure how you get the modfiied `M` flag there, this looks like git output. But the files you mentioned are part of `.gitignore` so there all should be fine.

I go an read again in autotools/automake to see if I use it correctly.

**Comment by agaida** [comment]
no sane user should be forced to run ./configure && make - left jokeing aside - the pure source should be enough. There are two type of people - the people who can build and install from source and the people who can't. The first part of people split into people that should and people that should not build from source - the second part is much bigger.

The people that should build from source will normally never do this - they create proper packages and are often called package maintainers. And the people who can't or shouldn't build from source normally install packages. So please be nice and release the pure sources ;)

anyways - autoreconf -f -i && ./configure && make will continue to work as expected - thats what the files HACKING, INSTALL, README or so are for.

**Comment by jubalh** [comment]
I still don't get what you want to say here. `./configure && make` are a normal procedure to build something.

**Comment by b4n** [comment]
"Sane" users should then probably pick up the sources from Git and checkout a tag -- or download the pure-source archive that's also available in both ZIP and TGZ formats :)

I tend to agree I'd rather myself run autoreconf myself than use the provided generated `configure` from a tarball, mostly because I'm paranoid and wouldn't trust the generated script not to have been altered in some way.  But that means I'm ready to deal with possible autoconf/automake version incompatibilities if they arise -- but no sane person would want that, nor generally could handle it.

Anyway, the tarballs provided here are totally standard.  If really you want to change how things are done, I'd rather make my point to the Autotools developers than to each and every person using them (almost correctly even, which is rare enough) :)
BTW, as suggested above, having the generated build system does also provide a lot of advantages to everyone, by i.e. being sure the resulting build system really has been tested and works (normally it'd be generated with `make distcheck`, which does a lot of meaningful checking).  And Autotools are known to be kind of fragile when changing versions (for both good and bad reasons), so it makes a lot of sense to have this part out of the way.

All this said your opening post is quite weird: only manually running `autoreconf` would result in changing the files you mentioned, and `make clean` definitely wouldn't remove them.

**Comment by agaida** [comment]
ok - my point is: a sane user will ever prefer one of the ways to install nudoku:
- apt install nudoku
- pacman -S nudoku
- yum install nudoku
- emerge nudoku
- add any other package manager here

I can only speak for me as a short term debian and arch user - but if i want some stuff i never build and install from sources, i prefer a clean package and install it via package manager of the choosen distribution.  And i really prefer to get things from the distribution, have to struggle with two 6 year old installations that aren't setup this way :D

**Comment by jubalh** [comment]
But nobody disagrees that distribution packages should be provided. I am still not sure what you want to say here.

**Comment by agaida** [comment]
it makes the work of a packager more easy if the packager can use a clean tar-ball - and with clean i think about sources that remain the same if i run (for debian) debuild  clean - sure, i think i can use release tags and git - but i have to figure out how this will work :)

**Comment by b4n** [comment]
Debian has all the tools required to build packages out of tarballs generated by Autotools -- many a Debian package are built this way (actually, probably the large majority of Autotools-using sw).  OK, on Debian they use dh_autoreconf which actually replaces those files, but the whole thing is still totally supposed to work seamlessly with tarballs juts like the ones here.

**Comment by agaida** [comment]
@b4n - and you really know what you are talking about in this special case?

**Comment by b4n** [comment]
@agaida no, as in I probably have made one single Debian package once in my life.  But I do know several packages are packaged from the tarballs, and I do know at least a few DDs _asked_ for proper Autotools release tarballs, and I have discussed with build system stuff with some of them.

**Comment by agaida** [comment]
Doing packages from tarballs is fine - i have only one problem with the current tarball: 
- i import the sources
- i run a debuild locally - fine, no problem
- i made a mistake and want to build the same sources again - in that case a dh_clean jumps in and clean up the previous build + the autogenerated files, next build attempt will break because of source changes that don't match with the original tar ball. 

I want to avoid that. It isn't rocket science to add a file with build instructions that include the generation of the auto generated files.

Edit: And yes, i would prefer --with autoreconf above --with autotools-dev or so.

**Comment by b4n** [comment]
OK, that's above my Debian package creation knowledge.  But really I can't imagine they don't have full support for building, rebuilding, cleaning, rebuilding and whatnot Autotools tarballs in some mostly-convenient way.

And even if it wasn't so, I still doubt "fixing" each downstream project not to use `make dist`ed tarballs is a sensible way to move forward.

But anyway, in the end it's not my call, and I don't have much to add here.

**Comment by jubalh** [comment]
I am pretty sure that this tarball is like it should be. I have asked and read so many sources now.
But still: the tar.xz is what I created using `make dist`, I did this because that's the preferred way AFAIK. And for everybody that does not like that there is the tar.gz which is created by GitHub from the Git tag. So I still don't get what the problem is. I think right from the start, both ways were enabled. The one where you just have to run `./configure && make` -> tar.xz and the one where you need to run `autoreconf` first.
Actually at first I only had the latter and then added the other for the **convenience** of users...

**Comment by nthykier** [comment]
Hi @agaida,

From Debian's PoV, I think this boils down to the difference between:

``` make
#!/usr/bin/make -f

%:
     dh $@
```
- vs

``` make
#!/usr/bin/make -f

%:
     dh $@ --with autoreconf
```

in the debian/rules file plus an extra package in Build-Depends. 
-  I cannot speak for Fedora or Gentoo though.

**Comment by agaida** [comment]
Hi @nthykier:
Nils, you are right, sometimes is kiss and doing nothing the best solution. Dunno why i needed --with autoreconf times ago, but never test it again with a pure dh $@.  dh $@ is indeed the solution :) Thanks.

@jubalh - i would say the package is finally done

**Comment by jubalh** [comment]
Great!
