### ISSUE TITLE
highlight numbers

### ISSUE THREAD

**Issue by amagnasco** [jubalh/nudoku#7]
Hi,

Not quite sure where you wanted me to write this? You should start up the wiki page! I like the game, it ran smoothly on arch (direct from here, not through aur). Given that we were talking about nsuds, I very much liked the minimalist graphic approach, as opposed to the "gaussian noise" background nsuds has. I did notice some functionality issues, mainly: lack of highlighting, notes, in-game ability to write in a new sudoku (on top of the init stream), and an in-game key for switching difficulty. These, of course, are very personal and subjective issues, and I don't know how they would fit in your vision of the program. I did have a lot of fun with it!

Also, the no-color init option should still highlight the squares in bold. Did you try seeing what happens if you switch the placement of the green and purple coloring? 

I liked it! Best,
Alessandro

**Comment by jubalh** [comment]
Ciao Alessandro,

Thanks for the positive feedback :) I am glad you like nudoku.
Yeah I tried to make it more minimal than nsuds, more to what I wanted it to be.
- What do you mean with lack of highlighting? The colors the computer put it should have a different color than what you type in. I didn't see what else could be highlighted :-)
- Notes - yeah I never implemented that because personally I dont use them. If you think this is a worthy feature and you have a nice idea about an implementation lets discuss this. Maybe you can add it if you want to.
- In-Game difficulty switching sounds useful to me. Personally I am quicker with pressing Q and then just replacethe last command I guess, so I never implemented this either. To keep it more minimal still.

About the no-color. I was under the impression that bold etc. also works only if you have a terminal with supports it. And I decided to have to modes: terminal who support colors+bold etc. and really basic terminal which dont. So each has its option.

**Comment by jubalh** [comment]
Just for the record:
Conversation started here: https://github.com/jubalh/nsuds/pull/1#issuecomment-173922776

**Comment by amagnasco** [comment]
I definitively like the visuals!

What I meant by highlighting is the nsuds r+# functionality in which I can press R and any number and it will change the background and foreground colors for every individual cell or note containing that number. It's fine for the lower difficulty settings where you can do it mentally, but for the higher difficulty levels, I usually have to resort to drawing it out on paper to see the relationships more clearly...

I haven't seen any good ways of implementing notes on ncurses unfortunately... I'll let you know if I think of something but it's unlikely.

re: no-color, why not [ if win32 then plain, else bold ] ? then the difference will be purely aesthetic! I'm pretty sure I've seen a python script for that...

**Comment by jubalh** [comment]
Aha! This r option makes sense. I think it would be nice to have this!

**Comment by amagnasco** [comment]
--> https://github.com/jubalh/nsuds/blob/master/src/marks.c
try integrating it and let me know how I can help

**Comment by jubalh** [comment]
Lets make this available for Hacktoberfest. If someone wants to add the `r` as suggested by @amagnasco:

> What I meant by highlighting is the nsuds r+# functionality in which I can press R and any number and it will change the background and foreground colors for every individual cell or note containing that number. It's fine for the lower difficulty settings where you can do it mentally, but for the higher difficulty levels, I usually have to resort to drawing it out on paper to see the relationships more clearly...

**Comment by jubalh** [comment]
Implemented in a slightly different way in https://github.com/jubalh/nudoku/pull/9
